# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
