# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-22 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180720_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='written',
        ),
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
