# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180722_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_authors', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='liked_quotes', to='users.User')),
                ('uploaded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_quotes', to='users.User')),
                ('written', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='users.Author')),
            ],
        ),
    ]
